# Python package
# Create and test a Python package on multiple Python versions.
# Add steps that analyze code, save the dist with the build record, publish to a PyPI-compatible index, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/python

trigger:
- main

pool:
  name: default

variables:
  name: 
    python.version=3.10

steps:
- script: |
    cd D:\Devprojects\flask calculator\flask-calculator
    python -m venv venv
    D:\Devprojects\flask calculator\flask-calculator\venv\Scripts\Activate.ps1
    python -m pip install --upgrade pip
    pip install -r requirements.txt
  displayName: 'Install dependencies'

- script: 
    START /B python app.py > webapp.txt
  displayName: 'run app.py'
